// example/components/vue/SizeTransition/index.vue
<template>
	<div class="size-transition" :style="{ height }">
		<div :id="id" ref="contentRef">
			<slot></slot>
		</div>
	</div>
</template>

<script setup lang="ts">
// @ts-nocheck
import { ref, onMounted, onBeforeUnmount, watch } from 'vue'

// 生成 UUID 的函数
const generateUUID = () => {
	return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
		const r = (Math.random() * 16) | 0
		const v = c === 'x' ? r : (r & 0x3) | 0x8
		return v.toString(16)
	})
}

const props = defineProps({
	minHeight: {
		type: Number,
		default: 0
	},
	initState: {
		type: Boolean,
		default: true
	}
})

const id = ref<string>(generateUUID())
const contentRef = ref<HTMLElement | null>(null)
const state = ref<boolean>(props.initState)
const height = ref<undefined | string>(undefined)
let observer: ResizeObserver | null = null

// 初始化尺寸观察
const initResizeObserver = (): void => {
	if (!contentRef.value) return

	observer = new ResizeObserver(entries => {
		for (const entry of entries) {
			const newHeight = entry.contentRect.height
			// 当处于展开状态时同步高度
			if (state.value) {
				height.value = `${newHeight + 3}px`
			}
		}
	})

	observer.observe(contentRef.value)
}

// 折叠方法
const contract = (): void => {
	if (!contentRef.value) return
	height.value = `${contentRef.value.offsetHeight}px`
	requestAnimationFrame(() => {
		height.value = `${props.minHeight}px`
		state.value = false
	})
}

// 展开方法
const expand = (): void => {
	if (!contentRef.value) return
	height.value = '0px'
	requestAnimationFrame(() => {
		height.value = `${contentRef.value!.offsetHeight + 3}px`
		state.value = true
	})
}

// 切换方法
const toggle = (): void => {
	state.value ? contract() : expand()
}

// 监听 initState 变化
watch(
	() => props.initState,
	newValue => {
		if (newValue) {
			expand()
		} else {
			contract()
		}
	}
)

// 生命周期
onMounted(() => {
	props.initState ? expand() : contract()
	initResizeObserver()
})

onBeforeUnmount(() => {
	observer?.disconnect()
})

// 暴露方法给父组件
defineExpose({
	contract,
	expand,
	toggle
})
</script>

<style scoped lang="scss">
.size-transition {
	width: 100%;
	overflow: hidden;
	transition: height 0.3s ease-in-out;
	will-change: height; // 启用硬件加速
}
</style>

// example/components/react/SizeTransition/index.tsx
import React, {
	useState,
	useEffect,
	useRef,
	ReactNode,
	useImperativeHandle,
	forwardRef
} from 'react';
import './size-transition.scss';

interface SizeTransitionProps {
	children: ReactNode;
	minHeight?: number;
	initState?: boolean;
}

export interface SizeTransitionHandles {
	expand: () => void;
	contract: () => void;
	toggle: () => void;
}

const SizeTransition = forwardRef<SizeTransitionHandles, SizeTransitionProps>(
	({ children, minHeight = 0, initState = true }, ref) => {
		const id = `size-transition-${Math.random().toString(36).substr(2, 9)}`;
		const contentRef = useRef<HTMLDivElement>(null);
		const [state, setState] = useState<boolean>(initState);
		const [height, setHeight] = useState<string | undefined>(undefined);
		const observerRef = useRef<ResizeObserver | null>(null);

		// 初始化尺寸观察
		const initResizeObserver = (): void => {
			if (!contentRef.current) return;

			observerRef.current = new ResizeObserver(entries => {
				for (const entry of entries) {
					const newHeight = entry.contentRect.height;
					// 当处于展开状态时同步高度
					if (state) {
						setHeight(`${newHeight + 3}px`);
					}
				}
			});

			observerRef.current.observe(contentRef.current);
		};

		// 折叠方法
		const contract = (): void => {
			if (!contentRef.current) return;
			setHeight(`${contentRef.current.offsetHeight}px`);
			requestAnimationFrame(() => {
				setHeight(`${minHeight}px`);
				setState(false);
			});
		};

		// 展开方法
		const expand = (): void => {
			if (!contentRef.current) return;
			setHeight('0px');
			requestAnimationFrame(() => {
				setHeight(`${contentRef.current!.offsetHeight + 3}px`);
				setState(true);
			});
		};

		// 切换方法
		const toggle = (): void => {
			state ? contract() : expand();
		};

		// 通过 ref 暴露方法
		useImperativeHandle(ref, () => ({
			expand,
			contract,
			toggle
		}));

		// 生命周期
		useEffect(() => {
			initState ? expand() : contract();
			initResizeObserver();

			return () => {
				observerRef.current?.disconnect();
			};
		}, []);

		return (
			<div className="size-transition" style={{ height }}>
				<div id={id} ref={contentRef}>
					{children}
				</div>
			</div>
		);
	}
);

export default SizeTransition;
